### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 38: invalid continuation byte

### ISSUE THREAD

**Issue by DaJiang7** [lululxvi/deeponet#22]
Hello, professor. I have some porblem.What's the way you coded?
I have the following error while running the code.

Traceback (most recent call last):
  File "E:/DeepONet/deeponet-master/src/deeponet_pde.py", line 285, in <module>
    main()
  File "E:/DeepONet/deeponet-master/src/deeponet_pde.py", line 281, in main
    run(problem, system, space, T, m, nn, net, lr, epochs, num_train, num_test)
  File "E:/DeepONet/deeponet-master/src/deeponet_pde.py", line 176, in run
    model.restore("model/model.ckpt-" + str(train_state.best_step), verbose=1)
  File "D:\ProgramData\Anaconda3\envs\donlu\lib\site-packages\deepxde\model.py", line 377, in restore
    self.saver.restore(self.sess, save_path)
  File "D:\ProgramData\Anaconda3\envs\donlu\lib\site-packages\tensorflow\python\training\saver.py", line 1289, in restore
    if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
  File "D:\ProgramData\Anaconda3\envs\donlu\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 383, in checkpoint_exists_internal
    if file_io.get_matching_files(pathname):
  File "D:\ProgramData\Anaconda3\envs\donlu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 350, in get_matching_files
    return get_matching_files_v2(filename)
  File "D:\ProgramData\Anaconda3\envs\donlu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 371, in get_matching_files_v2
    compat.as_bytes(pattern))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 38: invalid continuation byte

Process finished with exit code 1

**Comment by lululxvi** [comment]
It seems that the problem is due to Windows.

**Comment by DaJiang7** [comment]
> It seems that the problem is due to Windows.

OK，thank you very much！
