### ISSUE TITLE
AttributeError: 'Triple' object has no attribute 'transform_inputs'

### ISSUE THREAD

**Issue by jinjunyonggzh** [lululxvi/deeponet#25]
model.restore("model/model.ckpt-" + str(train_state.best_step) + ".ckpt", verbose=1)
 #model.restore("model/model.ckpt-" + str(train_state.best_step), verbose=1)
 safe_test(model, data, X_test, y_test)

Saving loss history to D:\LULU\deeponet-master1\deeponet-master\src\loss.dat ...
**Error: The network has multiple inputs, and saving such result han't been implemented.
Error: The network has multiple inputs, and plotting such result han't been implemented.**
Restoring model from model/model.ckpt-5000.ckpt ...

Traceback (most recent call last):
  File "D:/LULU/deeponet-master1/deeponet-master/src/deeponet_pde.py", line 285, in <module>
    main()
  File "D:\LULU/deeponet-master1/deeponet-master/src/deeponet_pde.py", line 281, in main
    run(problem, system, space, T, m, nn, net, lr, epochs, num_train, num_test)
  File "D:\LULU/deeponet-master1/deeponet-master/src/deeponet_pde.py", line 177, in run
    safe_test(model, data, X_test, y_test)
  File "D:\LULU\deeponet-master1\deeponet-master\src\utils.py", line 56, in safe_test
    y_pred.append(model.predict(data.transform_inputs(X_add)))
AttributeError: 'Triple' object has no attribute 'transform_inputs'

进程已结束,退出代码1

**Comment by lululxvi** [comment]
https://github.com/lululxvi/deeponet#installation-guide

**Comment by yejiwi** [comment]
> https://github.com/lululxvi/deeponet#installation-guide

Hi, I have the same issue and my code is already modified for the new version. What can I use instead of 'transform_inputs'?
