### ISSUE TITLE
KeyError: 'Glorot normalstacked'

### ISSUE THREAD

**Issue by fyxemily** [lululxvi/deeponet#35]
Hi,sir.
It confused me a lot that if I change 'stacked' to True, error happens:

Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/pythondeep/deeponet_pde.py", line 286, in <module>
    main()
  File "C:/Users/lenovo/PycharmProjects/pythondeep/deeponet_pde.py", line 269, in main
    net = dde.maps.DeepONet(
  File "C:\Users\lenovo\anaconda3\lib\site-packages\deepxde\nn\tensorflow_compat_v1\deeponet.py", line 60, in __init__
    self.kernel_initializer_stacked = initializers.get(
  File "C:\Users\lenovo\anaconda3\lib\site-packages\deepxde\nn\initializers.py", line 185, in get
    return INITIALIZER_DICT[identifier]
KeyError: 'Glorot normalstacked'

Process finished with exit code 1

Could you please give me a help! thanks alot

**Comment by lululxvi** [comment]
"stacked" one is used for stacked DeepONet, which is not suggested.
